apiVersion: v1
kind: PersistentVolume
metadata:
  name: ipfs-node03-cluster-pv
  namespace: ipfs
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /mnt/ipfs-cluster03
