apiVersion: v1
kind: Service
metadata:
  name: ipfs-node03-svc
  namespace: ipfs
spec:
  selector:
    sort: node03
  type: ClusterIP
  ports:
  - name: cluster-port
    port: 9096
    targetPort: 9096
  - name: swarm
    port: 4001
    targetPort: 4001
  - name: api
    port: 5001
    targetPort: 5001
  - name: gateway
    port: 8080
    targetPort: 8080
